plugins {
    id("com.android.library") version "8.2.2" apply false
    id("com.android.application") version "8.2.2" apply false
    id("io.deepmedia.tools.deployer") version "0.14.0" apply false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {
    javaSourceCompatibility = JavaVersion.VERSION_1_8
    javaTargetCompatibility = JavaVersion.VERSION_1_8


}
